config/routes.rb
Rails.application.routes.draw do

  get '/subjects', to: redirect('/departments')
  get '/semesters', to: redirect('/departments')
  get '/semesters/:id/', to: redirect('/departments')
  
  resources :subjects

  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  resources :courses

  resources :semesters

  get 'search/index'

  post 'search/index'

  resources :authors

  resources :departments

  resources :types

  resources :users

  get 'home/index'

  resources :items

  root 'home#index'

  match '/files/original/missing.png', to: 'errors#file_not_found', via: :all, as: :missing

  get 'sign_in' => "users#login"

  post 'sign_in' => "users#signin"

  get 'logout' => "users#logout"

  get 'about' => "home#about"

  post 'items/index'

  patch 'users/:id/changepassword', to:'users#changepasswordfunction', as:'changepassword'

  get 'users/:id/changepassword', to:'users#changepassword'

  post 'departments/:id' => "departments#show"

  post 'types/:id' => "types#show"

  post 'courses/:id' => "courses#show"

  get 'admin' => 'users#admin', as: 'admin'

  get 'statistics' => 'home#statistics', as: 'statistics'

  get 'course_statistics' => 'home#coursestatistics'
  
  get 'department_statistics' => 'home#departmentstatistics'

  get 'type_statistics' => 'home#typestatistics'

  post 'users/:id/removeprofilepic' => 'users#removeprofilepic', as:'removeprofilepic'

  get 'users/:id/changeimage' => 'users#changeimage', as: 'changeimage'

  get 'subjects/:id/choosestaff' => 'subjects#choosestaff', as: 'choosestaff'
  
  get 'subjects/:id/addstudenttosubject' => 'subjects#addstudenttosubject', as: 'addstudenttosubject'
 
  patch 'subjects/:id/addstudenttosubject' => 'subjects#addstudenttosubject'

  get 'items/:id/adddetails' => 'items#adddetails', as: 'adddetails'

  get 'users/:id/mysubjects' => 'users#mysubjects', as: 'mysubjects'

  get 'departments/:id/changedepimage' => 'departments#changedepimage', as: 'changedepimage'

  get 'subjects/:id/removeuserpath' => 'subjects#removeuser', as: 'removeuser'

  match '/404', to: 'errors#file_not_found', via: :all
  
  match '/500', to: 'errors#internal_server_error', via: :all

  match '/422', to: 'errors#unprocessable', via: :all
end

app/models/semester.rb
class Semester < ActiveRecord::Base
    has_many :items
    has_many :subjects
end

app/controllers/semesters_controller.rb
class SemestersController < ApplicationController
  before_action :set_semester, only: [:show, :edit, :update, :destroy]

  # GET /semesters
  # GET /semesters.json
  def index
    @semesters = Semester.all
  end

  # GET /semesters/1
  # GET /semesters/1.json
  def show
  end

  # GET /semesters/new
  def new
    @semester = Semester.new
  end

  # GET /semesters/1/edit
  def edit
  end

  # POST /semesters
  # POST /semesters.json
  def create
    @semester = Semester.new(semester_params)

    respond_to do |format|
      if @semester.save
        format.html { redirect_to @semester, notice: 'Semester was successfully created.' }
        format.json { render :show, status: :created, location: @semester }
      else
        format.html { render :new }
        format.json { render json: @semester.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /semesters/1
  # PATCH/PUT /semesters/1.json
  def update
    respond_to do |format|
      if @semester.update(semester_params)
        format.html { redirect_to @semester, notice: 'Semester was successfully updated.' }
        format.json { render :show, status: :ok, location: @semester }
      else
        format.html { render :edit }
        format.json { render json: @semester.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /semesters/1
  # DELETE /semesters/1.json
  def destroy
    @semester.destroy
    respond_to do |format|
      format.html { redirect_to semesters_url, notice: 'Semester was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_semester
      @semester = Semester.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def semester_params
      params.require(:semester).permit(:name)
    end
end

app/helpers/semesters_helper.rb
module SemestersHelper
end

app/views/semesters/_form.html.haml
= form_for @semester do |f|
  - if @semester.errors.any?
    #error_explanation
      %h2= "#{pluralize(@semester.errors.count, "error")} prohibited this semester from being saved:"
      %ul
        - @semester.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save', class:'btn btn-primary'

app/views/semesters/edit.html.haml
- if isadmin 
  %h1 Editing semester
  = render 'form'
- else
  .alert.alert-danger
    You are not permitted to access this page

app/views/semesters/index.html.haml
%h1 Listing semesters

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th
      
  %tbody
    - @semesters.each do |semester|
      %tr
        %td= semester.name
        %td= link_to 'Show', semester
        %td= link_to 'Edit', edit_semester_path(semester)
        %td= link_to 'Destroy', semester, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Semester', new_semester_path

app/views/semesters/new.html.haml
%h1 New semester

= render 'form'

= link_to 'Back', semesters_path

app/views/semesters/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @semester.name

= link_to 'Edit', edit_semester_path(@semester)
\|
= link_to 'Back', semesters_path