config/routes.rb
Rails.application.routes.draw do

  get '/subjects', to: redirect('/departments')
  get '/semesters', to: redirect('/departments')
  get '/semesters/:id/', to: redirect('/departments')
  
  resources :subjects

  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  resources :courses

  resources :semesters

  get 'search/index'

  post 'search/index'

  resources :authors

  resources :departments

  resources :types

  resources :users

  get 'home/index'

  resources :items

  root 'home#index'

  match '/files/original/missing.png', to: 'errors#file_not_found', via: :all, as: :missing

  get 'sign_in' => "users#login"

  post 'sign_in' => "users#signin"

  get 'logout' => "users#logout"

  get 'about' => "home#about"

  post 'items/index'

  patch 'users/:id/changepassword', to:'users#changepasswordfunction', as:'changepassword'

  get 'users/:id/changepassword', to:'users#changepassword'

  post 'departments/:id' => "departments#show"

  post 'types/:id' => "types#show"

  post 'courses/:id' => "courses#show"

  get 'admin' => 'users#admin', as: 'admin'

  get 'statistics' => 'home#statistics', as: 'statistics'

  get 'course_statistics' => 'home#coursestatistics'
  
  get 'department_statistics' => 'home#departmentstatistics'

  get 'type_statistics' => 'home#typestatistics'

  post 'users/:id/removeprofilepic' => 'users#removeprofilepic', as:'removeprofilepic'

  get 'users/:id/changeimage' => 'users#changeimage', as: 'changeimage'

  get 'subjects/:id/choosestaff' => 'subjects#choosestaff', as: 'choosestaff'
  
  get 'subjects/:id/addstudenttosubject' => 'subjects#addstudenttosubject', as: 'addstudenttosubject'
 
  patch 'subjects/:id/addstudenttosubject' => 'subjects#addstudenttosubject'

  get 'items/:id/adddetails' => 'items#adddetails', as: 'adddetails'

  get 'users/:id/mysubjects' => 'users#mysubjects', as: 'mysubjects'

  get 'departments/:id/changedepimage' => 'departments#changedepimage', as: 'changedepimage'

  get 'subjects/:id/removeuserpath' => 'subjects#removeuser', as: 'removeuser'

  match '/404', to: 'errors#file_not_found', via: :all
  
  match '/500', to: 'errors#internal_server_error', via: :all

  match '/422', to: 'errors#unprocessable', via: :all
end

app/models/author.rb
class Author < ActiveRecord::Base
    has_many :authorships
    has_many :items, through: :authorships
    accepts_nested_attributes_for :items
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.haml
= form_for @author do |f|
  - if @author.errors.any?
    #error_explanation
      %h2= "#{pluralize(@author.errors.count, "error")} prohibited this author from being saved:"
      %ul
        - @author.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save', class:'btn btn-primary'

app/views/authors/edit.html.haml
- if isadmin 
  %h1 Editing Author
  = render 'form'
- else
  .alert.alert-danger
    You are not permitted to access this page

app/views/authors/index.html.haml
%h1 Listing authors

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @authors.each do |author|
    %tr
      %td= author.name
      %td= link_to 'Show', author
      %td= link_to 'Edit', edit_author_path(author)
      %td= link_to 'Destroy', author, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Author', new_author_path

app/views/authors/new.html.haml
%h1 New author

= render 'form'

= link_to 'Back', authors_path

app/views/authors/show.html.haml
%p#notice= notice
.panel.panel-default
  .panel-heading
    %h3 Author Details
  .jumbotron
    .h1{style:"margin-top:0;padding-top:0"}
      = @author.name
  %table.table.table-bordered
    %tr
      %th Title
      %th Course
      %th Department
    - @author.items.each do |item|
      %tr
        %td 
          = link_to item.title,item
        %td
          - if item.course
            = link_to item.course.name,item.course
        %td
          - if item.department
            = link_to item.department.name,item.department