config/routes.rb
Rails.application.routes.draw do

  get '/subjects', to: redirect('/departments')
  get '/semesters', to: redirect('/departments')
  get '/semesters/:id/', to: redirect('/departments')
  
  resources :subjects

  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  resources :courses

  resources :semesters

  get 'search/index'

  post 'search/index'

  resources :authors

  resources :departments

  resources :types

  resources :users

  get 'home/index'

  resources :items

  root 'home#index'

  match '/files/original/missing.png', to: 'errors#file_not_found', via: :all, as: :missing

  get 'sign_in' => "users#login"

  post 'sign_in' => "users#signin"

  get 'logout' => "users#logout"

  get 'about' => "home#about"

  post 'items/index'

  patch 'users/:id/changepassword', to:'users#changepasswordfunction', as:'changepassword'

  get 'users/:id/changepassword', to:'users#changepassword'

  post 'departments/:id' => "departments#show"

  post 'types/:id' => "types#show"

  post 'courses/:id' => "courses#show"

  get 'admin' => 'users#admin', as: 'admin'

  get 'statistics' => 'home#statistics', as: 'statistics'

  get 'course_statistics' => 'home#coursestatistics'
  
  get 'department_statistics' => 'home#departmentstatistics'

  get 'type_statistics' => 'home#typestatistics'

  post 'users/:id/removeprofilepic' => 'users#removeprofilepic', as:'removeprofilepic'

  get 'users/:id/changeimage' => 'users#changeimage', as: 'changeimage'

  get 'subjects/:id/choosestaff' => 'subjects#choosestaff', as: 'choosestaff'
  
  get 'subjects/:id/addstudenttosubject' => 'subjects#addstudenttosubject', as: 'addstudenttosubject'
 
  patch 'subjects/:id/addstudenttosubject' => 'subjects#addstudenttosubject'

  get 'items/:id/adddetails' => 'items#adddetails', as: 'adddetails'

  get 'users/:id/mysubjects' => 'users#mysubjects', as: 'mysubjects'

  get 'departments/:id/changedepimage' => 'departments#changedepimage', as: 'changedepimage'

  get 'subjects/:id/removeuserpath' => 'subjects#removeuser', as: 'removeuser'

  match '/404', to: 'errors#file_not_found', via: :all
  
  match '/500', to: 'errors#internal_server_error', via: :all

  match '/422', to: 'errors#unprocessable', via: :all
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :items
    belongs_to :department
    belongs_to :course
    
    has_many :subjectrelations, class_name:'Subjectrelations'
    has_many :subjects, through: :subjectrelations
    accepts_nested_attributes_for :subjects

    validates :username, uniqueness: true
    validates :department_id, presence: true, if: :notadmin?
    validates :designation, presence: true
    validates :password, :confirmation => true
    validates :newpassword, :confirmation => true, :on => :changepassword
    validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, :message => ": Format invalid", :on => :update
    validates_format_of :mobile, :with => /\A\w{10}\z/i, :message => ": Format invalid", :on => :update
    validates_format_of :phone, :with => /\A\w{0,4}[-]?\w{6,8}\z/i, :message => ": Format invalid", :on => :update
    scope :designation, ->{ where(designation:"faculty")}

    has_attached_file :image, :url => "/assets/images/profilepics/:usrname_:style.:extension", :path=>":rails_root/public/assets/images/profilepics/:usrname_:style.:extension", :styles => {:thumbnail => "25x25#", :small =>"125x125#", :large => "500x500>"}
    validates_attachment_content_type :image, :content_type =>/image/
 
    Paperclip.interpolates('usrname') do |attachment, style|
        attachment.instance.username.gsub(" ","_").gsub(".","")
    end

    def notadmin?
        if not designation == 'admin'
            return true
        else
            return false
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :changepassword, :changepasswordfunction, :removeprofilepic, :changeimage, :mysubjects]
  helper_method :isuploader, :isadmin, :isuseruploader

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  def login
  end

  def signin
      @username = params[:user][:username]
      @password = params[:user][:password]
      @password_input_sha = Digest::SHA1.hexdigest(params[:user][:password]) 
      @users = User.where(:username => @username)
      if not @users.empty?
          @currentuser = @users.first
          if @currentuser.password == @password_input_sha then
              session[:user] = @users.first.username
              redirect_to root_path
          else
              redirect_to sign_in_path, notice:"Incorrect"
          end
      else
          redirect_to sign_in_path, notice:"Incorrect"
      end
  end

  def admin
  end

  def logout
      session.delete(:user)
      redirect_to root_path
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @password_input = params[:user][:password]
    @password_input_confirmation = params[:user][:password_confirmation]
    @password_input_sha = Digest::SHA1.hexdigest(@password_input)
    @password_input_confirmation_sha = Digest::SHA1.hexdigest(@password_input_confirmation)
    @newparams = user_params
    @newparams[:password] = @password_input_sha
    @newparams[:password_confirmation] = @password_input_confirmation_sha
    @user = User.new(@newparams)
    @user.department = Department.where("name = ?",params[:user][:department][:name]).first
    @user.course = Course.where("name = ?",params[:user][:course][:name]).first if params[:user][:course]
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
        @params = user_params
        @params[:batchbegin] = DateTime.new(params[:user][:batchbegin].to_i) if params[:user][:batchbegin]
        @params[:batchend] = DateTime.new(params[:user][:batchend].to_i) if params[:user][:batchend]
      if @user.update(@params)
        @user.department = Department.where("name = ?",params[:user][:department][:name]).first if params[:user][:department]
        @user.course = Course.where("name = ?",params[:user][:course][:name]).first if params[:user][:course]
        @user.save
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def removeprofilepic
      @user.image = nil
      @user.save
      redirect_to @user
  end

  def changeimage
  end

  def changepassword
  end

  def changepasswordfunction
      puts params[:user][:password]
      @currentpassword = params[:user][:password]
      @newpassword_input = params[:user][:newpassword]
      @newpassword_input_confirmation = params[:user][:newpassword_confirmation]
      @currentpassword_sha = Digest::SHA1.hexdigest(@currentpassword)
      if @currentpassword_sha != @user.password then
          redirect_to changepassword_path, notice:"Current Password Incorrect"
      else
          if @newpassword_input != @newpassword_input_confirmation then
              redirect_to changepassword_path, notice: "Passwords do not match"
          else
              @newpassword_input_sha = Digest::SHA1.hexdigest(@newpassword_input)
              @user.update_attribute(:password,@newpassword_input_sha)
              redirect_to @user
          end
      end

  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if @user == User.where("username = ?",session[:user])
        session.delete(:user)
    end
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      if params[:id]
          @user = User.find(params[:id])
      else
          @user = User.where("username = ?",session[:user]).first
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :name, :designation, :department, :admin, :password_confirmation, :newpassword, :new_password_confirmation, :image, :admissionnumber, :dob, :address, :bloodgroup, :email, :phone, :mobile, :privateprofile, :course, :batchbegin, :batchend)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_for @user,:html=>{class:"form-signin"} do |f|
  - if @user.errors.any?
    .alert.alert-danger{role:"alert"}
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.text_field :username, placeholder:"User name", class:"form-control", required:"true"
  .field
    = f.password_field :password, placeholder: "Password", class:"form-control", required:"true"
  .field
    = f.password_field :password_confirmation, placeholder: "Confirm Password", class:"form-control", required:"true"
  .field
    = f.text_field :name, placeholder:"Name", class:"form-control", required:"true"
  .field
    - if params[:designation]
      - @des = params[:designation]
    - elsif @user.designation
      - @des = @user.designation
    - else
      - @des = ""
    - puts "Designation is : " + @des
    = f.select :designation, options_for_select({"Admin"=>"admin", "HOD"=>"hod", "Faculty"=>"faculty","Student"=>"student"},@des), {include_blank:"Account Type"}, {class:"selectpicker"}
  .field
    = f.fields_for :department do |department_form|
      = department_form.select :name, options_from_collection_for_select(Department.all,'name','name'), {include_blank:"Department"}, {class:"selectpicker"}
  .field
    .input-group
      %span.input-group-btn
        %span.btn.btn-success.btn-file
          = f.file_field :image
          Browse Profile Picture
      %input.form-control#filetext{type:"text"}
  .actions
    = f.submit 'Save', class:"btn btn-primary", style:"width:100%"
:javascript
    $(document).on('change', '.btn-file :file', function() {
    var input = $(this),
    numFiles = input.get(0).files ? input.get(0).files.length : 1,
    label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
    input.trigger('fileselect', [numFiles, label]);
    });

    $(document).ready( function() {
    $('.btn-file :file').on('fileselect', function(event, numFiles, label) {
    console.log(numFiles);
    console.log(label);
    document.getElementById('filetext').value = label;
    reader.readAsDataURL(file);
    });
    });

app/views/users/_login.html.haml
%h1{style:"text-align:center"} Sign In
= form_for(@user=User.new, :url=>sign_in_path) do |f|
  = f.text_field :username,class:"form-control",placeholder:"Username"
  %br
  = f.text_field :password,type:"password",class:"form-control",placeholder:"Password"
  %br
  = button_tag "Sign In", class:"btn", style:"width:100%"

app/views/users/_useredit.html.haml
= form_for @user,:html=>{class:"form-signin"} do |f|
  - if @user.errors.any?
    .alert.alert-danger{role:"alert"}
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.text_field :name, placeholder:"Name", class:"form-control", required:"true"
  - if isadmin
    .field
      - if @user.designation
        - @des = @user.designation
      - elsif params[:designation]
        - @des = params[:designation]
      - else
        - @des = ""
      = f.select :designation, options_for_select({"Admin"=>"admin","HOD"=>"hod","Faculty"=>"faculty","Student"=>"student"},@des), {include_blank:"Account Type"}, {class:"selectpicker"}
    .field
      - if @user.batchbegin
        - @bbegin = @user.batchbegin.year.to_s
        - puts "Batch Begin" + @bbegin
      - else
        - @bbegin = ""
      = f.select :batchbegin, options_for_select(2000..Time.now.year+6,@bbegin), {include_blank: "Batch Begin Year"}, {class:"selectpicker"}
    .field
      - if @user.batchend
        - @bend = @user.batchend.year.to_s
        - puts "Batch End : " + @bend
      - else
        - @bend = ""
      = f.select :batchend, options_for_select(Time.now.year-5..Time.now.year+6,@bend), {include_blank: "Batch End Year"}, {class:"selectpicker"}
  .field
    - if @user.course
      - @cou = @user.course.name
    - elsif params[:course]
      - @cou = params[:course]
    - else
      - @cou = ""
    = f.fields_for :course do |course_form|
      = course_form.select :name, options_from_collection_for_select(Course.all,'name','name',@cou), {include_blank:"Course"}, {class:"selectpicker"}
  .field
    - if @user.department
      - @dep = @user.department.name
    - elsif params[:department]
      - @dep = params[:department]
    - else
      - @dep = ""
    = f.fields_for :department do |department_form|
      = department_form.select :name, options_from_collection_for_select(Department.all,'name','name',@dep), {include_blank:"Department"}, {class:"selectpicker"}
  .field
    = f.text_field :admissionnumber, class:"form-control", placeholder:"Admission Number"
  .field
    = f.text_field :dob, class:"form-control datepicker", placeholder:"Date of Birth (dd-mm-yyyy)"
  .field
    = f.text_area :address, class:"form-control", placeholder:"Address"
  .field
    = f.text_field :bloodgroup, class:"form-control", placeholder:"Blood Group"
  .field
    = f.text_field :email, class:"form-control", placeholder:"Email ID"
  .field
    = f.text_field :phone, class:"form-control", placeholder:"Phone Number"
  .field
    .input-group
      %span.input-group-addon
        +91
      = f.text_field :mobile, class:"form-control", placeholder:"Mobile Number"
  .field
    %label.checkbox.inline
      Keep my profile hidden from other users
      = f.check_box :privateprofile, class:"checkbox inline"
  .actions
    = f.submit 'Save', class:"btn btn-primary", style:"width:100%"

app/views/users/admin.html.haml
.panel.panel-default
  .panel-heading
    %h3 Admin Panel
  %table.table.table-bordered{style:"text-align:center"}
    %tr
      %td
        %a{href:users_path}
          = image_tag 'usericon.png', width:"20%"
          %br
          Edit Users
      %td
        %a{href:departments_path}
          = image_tag 'departments.png', width:"20%"
          %br
          Edit Departments
      /        
        %td
          %a{href:courses_path}
            = image_tag 'courses.png', width:"46%"
            %br
            Edit Courses
      %td
        %a{href:types_path}
          = image_tag 'types.png', width:"20%"
          %br
          Edit Resource Types
      %td
        %a{href:statistics_path}
          = image_tag 'statistics.png', width:"60%"
          %br
          View Statistics
 

app/views/users/changeimage.html.haml
- if isadmin or @user == User.where("username = ?",session[:user]).first
  .row
    .col-md-6
      - if @user.image_file_name
        - @loc = @user.image.url
      - else
        - @loc = "usericon.png"
      = image_tag @loc, width:"50%", id:"previewimage"
      %br
      %br
    .col-md-6
      = button_to "Remove Picture", removeprofilepic_path, method:"post", data: {confirm: "Are you sure? You can choose your new profile picture at end of this page instead of deleting."}, class:"btn btn-danger" if @user.image_file_name
      = form_for @user,:html=>{class:"form-signin"} do |f|
        %br
        %br
        .field
          .input-group
            %span.input-group-btn
              %span.btn.btn-success.btn-file
                = f.file_field :image
                Browse Picture
            %input.form-control#filetext{type:"text"}
            - puts @user.username
        .actions
          = f.submit 'Save', class:"btn btn-primary", style:"width:50%"
- else
  .alert.alert-danger
    You are not permitted to access this page
:javascript
    $(document).on('change', '.btn-file :file', function() {
    var input = $(this),
    numFiles = input.get(0).files ? input.get(0).files.length : 1,
    label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
    input.trigger('fileselect', [numFiles, label]);
    });
  $(document).ready( function() {
    $('.btn-file :file').on('fileselect', function(event, numFiles, label) {
    console.log(numFiles);
    console.log(label);
    document.getElementById('filetext').value = label;
    var preview = document.getElementById('previewimage');
    var file    = document.querySelector('input[type=file]').files[0];
    var reader  = new FileReader();
    reader.onloadend = function (e) {
    preview.src = e.target.result;
    };
    reader.readAsDataURL(file);
    });
    });

app/views/users/changepassword.html.haml
.alert.alert-danger{role:"alert"}
  =notice
= form_for @user,:url=>changepassword_path,:html=>{class:"form-signin"} do |f|
  - if @user.errors.any?
    .alert.alert-danger{role:"alert"}
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.password_field :password, placeholder: "Password", class:"form-control", required:"true"
  .field
    = f.password_field :newpassword, placeholder: "New Password", class:"form-control", required:"true"
  .field
    = f.password_field :newpassword_confirmation, placeholder: "Confirm New Password", class:"form-control", required:"true"
  .actions
    = f.submit 'Save', class:"btn btn-primary", style:"width:100%"

app/views/users/edit.html.haml
%h1{style:"text-align:center"} 
  Editing 
  = @user.username
- if isadmin or session[:user] == @user.username
  #editform{style:"width:50%;text-align:center;margin:0 auto"}
    = render 'useredit'
- else
  .alert.alert-danger{role:"alert"}
    You are not permitted to access this page

app/views/users/index.html.haml
%ul#tabs.nav.nav-tabs{"data-tabs"=>"tabs"}
  %li.active
    %a{href:"#student", "data-toggle" => "tab"}
      Student
  %li
    %a{href:"#faculty", "data-toggle" => "tab"}
      Faculties
  %li
    %a{href:"#admin", "data-toggle" => "tab"}
      Administrators
#my-tab-content.tab-content
  .tab-pane.active#student
    %table.table.table-bordered{style:"text-align:center"}
      - @cnt = 0
      - User.where("designation = 'student'").each do |student|
        %td
          %a{href:user_path(student)}  
            - if student.image_file_name
              = image_tag student.image.url, width:"100px" 
            - else
              = image_tag 'student.png', width:"100px"
            %br
            = student.name
            - @cnt += 1
        - if @cnt%3 == 0
          %tr
      - if isadmin
        %td
          %a{href:new_user_path}
            = image_tag "add.png", width:"100px"
            %br
            Add New Student
  .tab-pane#faculty
    %table.table.table-bordered{style:"text-align:center"}
      %tr
      - @cnt = 1
      - User.where("designation = 'faculty'").each do |faculty|
        %td
          %a{href:user_path(faculty)}  
            - if faculty.image_file_name
              = image_tag faculty.image.url, width:"100px" 
            - else
              = image_tag 'faculty.png', width:"100px"
            %br
            = faculty.name
            - @cnt += 1
        - if @cnt%3 == 0
          %tr
      - if isadmin
        %td
          %a{href:new_user_path}
            = image_tag "add.png", width:"100px"
            %br
            Add New Faculty
  .tab-pane#admin
    %table.table.table-bordered{style:"text-align:center"}
      - @cnt = 0
      - User.where("designation = 'admin'").each do |admin|
        %td
          %a{href:user_path(admin)}  
            - if admin.image_file_name
              = image_tag admin.image.url, width:"100px" 
            - else
              = image_tag 'admin.png', width:"100px"
            %br
            = admin.name
            - @cnt += 1
        - if @cnt%3 == 0
          %tr
      - if isadmin
        %td
          %a{href:new_user_path}
            = image_tag "add.png", width:"100px"
            %br
            Add New Administrator

app/views/users/login.html.haml
- if notice and notice!=""
  .alert.alert-danger
    = notice
- if session[:user]
  .alert.alert-success
    You are already logged in
- else
  #signinform{style:"margin:0 auto;width:50%"}
    = render 'login'

app/views/users/mysubjects.html.haml
%h1{style:"text-align:center"} My Subjects
%table.table.table-bordered
  - @subjects = @user.subjects.sort_by &:code
  - puts @subjects

  - @subjects.each do |subject|
    %tr
      %td{style:"width:30%"}
        = subject.code
        %h4{style:"margin:0;"}
          = link_to subject.name,subject,{style:"color:blue"}
        %h5
          = link_to User.find(subject.faculty_id).name,User.find(subject.faculty_id) if subject.faculty_id and subject.faculty_id > 0
      %td
        = subject.description.html_safe if subject.description

app/views/users/new.html.haml
- if isadmin
  %h1 New user

  = render 'form'
- else
  .alert.alert-danger
    You don't have permission to add new user. Only an administrator can do that.

app/views/users/show.html.haml
%p#notice= notice
/%select#thisisaselect
.panel.panel-default
  .panel-heading
    %h3 User Details
  .jumbotron
    .row
      .col-md-6
        .h2{style:"margin-top:0;padding-top:0"}
          = @user.name
      .col-md-6{style:"text-align:center"}
        = image_tag @user.image.url(:small) if @user.image_file_name
        %br
        %br
        - if isadmin or session[:user] == @user.username
          .btn-group
            %button.btn.btn-primary.dropdown-toggle{"data-toggle"=>"dropdown","aria-expanded"=>"false"} 
              Profile Actions
              %span.caret
            %ul.dropdown-menu{role:"menu"}
              %li
                = link_to "Edit Profile",edit_user_path(@user), method: :get
              %li
                = link_to "Change Password", changepassword_path(@user), method: :get
              %li
                - if @user.image_file_name
                  - @txt = "Change Image"
                - else
                  - @txt = "Upload Image"
                = link_to @txt, changeimage_path(@user), method: :get
          = link_to "Delete Account", @user, method: :delete, data: {confirm: "Are you sure? All your uploads will also be deleted."}, class:"btn btn-danger"
    .row
      %ul#tabs.nav.nav-tabs{"data-tabs"=>"tabs"}
        %li.active
          %a{href:"#academic", "data-toggle" => "tab"}
            Academic Details
        - if @user.privateprofile != true or isadmin or @user.username == session[:user]
          %li
            %a{href:"#personal", "data-toggle" => "tab"}
              Personal Details
      #my-tab-content.tab-content
        .tab-pane.active{:id => "academic"}
          %table.table
            %tr
              %td{width:"20%"} Designation
              %td
                = @user.designation if @user.designation
            %tr
              - if @user.designation == 'student'
                %td{width:"10%"} Course
                %td
                  = @user.course.name if @user.course
                %tr
                  %td{width:"10%"} Batch
                  %td
                    = @user.batchbegin.year.to_s + " - " + @user.batchend.year.to_s if @user.batchbegin and @user.batchend
                %tr
                  %td{width:"10%"} Admission Number
                  %td
                    = @user.admissionnumber if @user.admissionnumber
            %tr
              %td{width:"10%"} Department
              %td
                = @user.department.name if @user.department

        - if @user.privateprofile != true or isadmin or @user.username == session[:user]
          .tab-pane{:id => "personal"}
            %table.table
              %tr
                %td{width:"20%"} Address
                %td
                  = @user.address.gsub("\n","<br />").html_safe if @user.address
              %tr
                %td{width:"10%"} 
                  Date of Birth
                %td
                  = @user.dob if @user.dob
              %tr
                %td{width:"10%"} Blood Group
                %td
                  = @user.bloodgroup if @user.bloodgroup
              %tr
                %td{width:"10%"} Email Id
                %td
                  = mail_to @user.email if @user.email
              %tr
                %td{width:"10%"} Phone
                %td
                  = @user.phone if @user.phone
              %tr
                %td{width:"10%"} Mobile
                %td
                  = @user.mobile if @user.mobile

- if isuseruploader(@user) and @user.items.count > 0
  .panel.panel-default
    .panel-heading
      %h3 Uploads by user
    %table.table.table-bordered{style:"text-align:center"}
      %tr
      - @cnt = 0
      - @user.items.each do |item|
        - if @cnt%3==0 then
          %tr
        %td
          %a.image{href:item_path(item)}
            - if item.type
              - @location = item.type.image.url
            - else
              - @location = "subjectnote.png"
            = image_tag @location, width:"20%"
          %br
          = link_to item.title,item
          %br
          = item.course.name if item.course
          = item.department.name if item.department
          = " - Semester " + item.semester.name if item.semester
          - @cnt += 1
/
  %script
    $(document).ready(function(){
    var a = ""
    - cnt = 0;
    - User.all.each do |user|
      var opt#{cnt} = document.createElement("option")
      opt#{cnt}.value = '#{user.username}'
      opt#{cnt}.innerHTML = '#{user.username}'
      document.getElementById('thisisaselect').appendChild(opt#{cnt});
      - cnt += 1
    });