config/routes.rb
Rails.application.routes.draw do

  get '/subjects', to: redirect('/departments')
  get '/semesters', to: redirect('/departments')
  get '/semesters/:id/', to: redirect('/departments')
  
  resources :subjects

  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  resources :courses

  resources :semesters

  get 'search/index'

  post 'search/index'

  resources :authors

  resources :departments

  resources :types

  resources :users

  get 'home/index'

  resources :items

  root 'home#index'

  match '/files/original/missing.png', to: 'errors#file_not_found', via: :all, as: :missing

  get 'sign_in' => "users#login"

  post 'sign_in' => "users#signin"

  get 'logout' => "users#logout"

  get 'about' => "home#about"

  post 'items/index'

  patch 'users/:id/changepassword', to:'users#changepasswordfunction', as:'changepassword'

  get 'users/:id/changepassword', to:'users#changepassword'

  post 'departments/:id' => "departments#show"

  post 'types/:id' => "types#show"

  post 'courses/:id' => "courses#show"

  get 'admin' => 'users#admin', as: 'admin'

  get 'statistics' => 'home#statistics', as: 'statistics'

  get 'course_statistics' => 'home#coursestatistics'
  
  get 'department_statistics' => 'home#departmentstatistics'

  get 'type_statistics' => 'home#typestatistics'

  post 'users/:id/removeprofilepic' => 'users#removeprofilepic', as:'removeprofilepic'

  get 'users/:id/changeimage' => 'users#changeimage', as: 'changeimage'

  get 'subjects/:id/choosestaff' => 'subjects#choosestaff', as: 'choosestaff'
  
  get 'subjects/:id/addstudenttosubject' => 'subjects#addstudenttosubject', as: 'addstudenttosubject'
 
  patch 'subjects/:id/addstudenttosubject' => 'subjects#addstudenttosubject'

  get 'items/:id/adddetails' => 'items#adddetails', as: 'adddetails'

  get 'users/:id/mysubjects' => 'users#mysubjects', as: 'mysubjects'

  get 'departments/:id/changedepimage' => 'departments#changedepimage', as: 'changedepimage'

  get 'subjects/:id/removeuserpath' => 'subjects#removeuser', as: 'removeuser'

  match '/404', to: 'errors#file_not_found', via: :all
  
  match '/500', to: 'errors#internal_server_error', via: :all

  match '/422', to: 'errors#unprocessable', via: :all
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
        @items = Item.all
        @conditions={}
        if params.has_key?(:department) then
            @conditions["department"]=params[:department]
        end
        if params.has_key?(:type) then
            @conditions["type"]=params[:type]
        end
        if params.has_key?(:semester) then
            @conditions["semester"]=params[:semester]
        end
        puts @conditions
        @querystring="course_id = " + @course.id.to_s
        @conditions.each do |key,value|
            if not value=='' then
                if not @querystring=="" then
                    @querystring = @querystring + " and "
                end
                if key=="department" then
                    @departmentid = Department.where("name = ?",value).first.id
                    @querystring = @querystring+"department_id = "+@departmentid.to_s
                elsif key=="type" then
                    @typeid = Type.where("name = ?",value).first.id
                    @querystring = @querystring+"type_id = "+@typeid.to_s
                elsif key=="semester" then
                    @semid = Semester.where("name = ?",value).first.id
                    @querystring = @querystring+"semester_id = "+@semid.to_s
                end
            end
        end
        puts @querystring
        @items = Item.where(@querystring)


  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :image)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.haml
= form_for @course do |f|
  - if @course.errors.any?
    #error_explanation
      %h2= "#{pluralize(@course.errors.count, "error")} prohibited this course from being saved:"
      %ul
        - @course.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.text_field :name, class:"form-control", placeholder: "Name"
  .field
    .input-group
      %span.input-group-btn
        %span.btn.btn-success.btn-file
          = f.file_field :image
          Browse Course Image
      %input.form-control#filetext{type:"text"}
  .actions
    = f.submit 'Save', class:"btn btn-primary", style:"width:100%"
:javascript
    $(document).on('change', '.btn-file :file', function() {
    var input = $(this),
    numFiles = input.get(0).files ? input.get(0).files.length : 1,
    label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
    input.trigger('fileselect', [numFiles, label]);
    });

    $(document).ready( function() {
    $('.btn-file :file').on('fileselect', function(event, numFiles, label) {
    console.log(numFiles);
    console.log(label);
    document.getElementById('filetext').value = label;
    reader.readAsDataURL(file);
    });
    });

app/views/courses/edit.html.haml
- if isadmin 
  %h1 Editing course
  = render 'form'
- else
  .alert.alert-danger
    You are not permitted to access this page

app/views/courses/index.html.haml
%h1 Listing courses
= image_tag "btech.png"
%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th
      
  %tbody
    - @courses.each do |course|
      %tr
        %td= course.name
        %td= link_to 'Show', course
        %td= link_to 'Edit', edit_course_path(course)
        %td= link_to 'Destroy', course, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Course', new_course_path

app/views/courses/new.html.haml
%h1 New course

= render 'form'

= link_to 'Back', courses_path

app/views/courses/show.html.haml
%p#notice= notice
.panel.panel-default
  .panel-heading
    %h3 Course Details
  .jumbotron
    .row
      .col-md-8
        .h1{style:"margin-top:0;padding-top:0"}
          = @course.name
      .col-md-4{style:"text-align:right"}
        = image_tag @course.image.url, width:"100px" if @course.image
= form_tag(course_path(@course), method:"post", class:"navbar-form") do |f|
  .row{style:"text-align:center"}
    .col-md-3
      = select_tag :type, options_from_collection_for_select(Type.all,'name','name',params[:type]), prompt:"Type", class:"selectpicker form-control"
    .col-md-3
      = select_tag :department, options_from_collection_for_select(Department.all,'name','name',params[:department]), prompt:"Department", class:"selectpicker form-control"
    .col-md-3
      = select_tag :semester, options_from_collection_for_select(Semester.all,'name','name',params[:semester]), prompt:"Semester", class:"selectpicker form-control"
    .col-md-3
      = button_tag "Go", class:"btn btn-primary", style:"width:100%"
%br
%table.table.table-bordered{style:"text-align:center"}
  %tr
  - @cnt = 0
  - @items.each do |item|
    - if @cnt%3==0 then
      %tr
    %td
      %a.image{href:item_path(item)}
        = image_tag item.type.image.url, width:"20%" if item.type
      %br
      = link_to item.title,item
      %br
      = item.course.name if item.course
      = item.department.name if item.department
      = " - Semester " + item.semester.name if item.semester
      - @cnt += 1